### PR TITLE
fix: update walletlink-connector to 6.2.7

### PR DESCRIPTION
**Pull request by brendanww**
Update to walletlink-connector 6.2.7 which includes a version of walletlink that has support for addEthereumChain/switchEthereumChain requests

Also enables the network switcher menu for any of the three coinbase wallet wallet implementations (extension, in-app dapp browser, and walletlink)

### CODE REVIEW

**Comment by brendanww** [comment]
@omakasebar would it be possible to get 👀 on this PR

**Comment by brendanww** [comment]
@jiro-ono would it be possible to get 👀 on this PR? CB Wallet users having the in-dapp network switcher menu would be a large UX win.

**Comment by jiro-ono** [comment]
@brendanww Seems to be throwing a lot of errors for me currently. It's having an issue with it fetching the block number when actually getting connected to the cb extension.

I'll look into this some more over the next few days though / @ me again if you find out what these bugs may be (not sure if you see on your end)

**Comment by brendanww** [comment]
@jiro-ono I am seeing errors with getting block height, but they appear to be due to the alchemy url specified returning 403. I don't think the issue is tied to CB Wallet.

**Comment by matthewlilley** [comment]
> @jiro-ono I am seeing errors with getting block height, but they appear to be due to the alchemy url specified returning 403. I don't think the issue is tied to CB Wallet.

ACK, will check this out in a moment.

**Comment by brendanww** [comment]
@matthewlilley Please let me know if there is any change I can make to help land this. It will be a much better experience for users to use the network switcher menu within sushiswap rather than having to go into app settings.

**Comment by matthewlilley** [comment]
@brendanww can you clean up PR to not include translations, ping me and I'll get this merged immediately.

**Comment by matthewlilley** [comment]
Ah, you already did. Much appriciated!!!

**Pull request merged**
