### PR TITLE
feat: adds OpenMEV protection and removes deprecated ArcherDAO implementation

### PR DESCRIPTION
**Pull request by aldoborrero**
This PR presents the following:

- All submitted TXs will receive MEV protection (with no gas refunding) if the user activates OpenMEV in settings.
- It removes deprecated ArcherDAO implementation.

Yet to be added (in a separate PR):

- Support to arb. based gas refunding TXs

Partially closes #392

### CODE REVIEW

**Comment by sambacha** [comment]
@matthewlilley @jiro-ono 

also wouldn't mind feedback from @gasperbr and @omakasebar if you have the bandwith

**Comment by matthewlilley** [comment]
@aldoborrero @sambacha I'm back on Monday so will try and get this in then.

**Comment by sambacha** [comment]
> @aldoborrero @sambacha I'm back on Monday so will try and get this in then.
💯  🎉 Happy New Years and appreciate the follow up @matthewlilley

**Comment by sambacha** [comment]
can see preview deployment here https://github.com/manifoldfinance/sushiswap-interface/pull/95

**Comment by aldoborrero** [comment]
Closed in favor of #525

**Pull request closed without merging**
