### PR TITLE
feat: add @davatar/react for ENS avatar support

### PR DESCRIPTION
**Pull request by carlosdp**
## Description

This PR adds robust avatar image lookup support for ENS `avatar` text record lookup for the logged in user's avatar, using the [@davatar/react](https://github.com/TBDAO/davatar-helpers/tree/master/packages/react) package, which seeks to fulfill the spec outlined in [avatars.md](https://gist.github.com/Arachnid/9db60bd75277969ee1689c8742b75182).

Our goal is to push forward usage of decentralized avatars using ENS, and this PR works toward making sure as people do so, they see their chosen avatar in the SushiSwap app!

The component defaults to the sushi chef, exactly as SushiSwap currently behaves today, so if no avatar has been set by the user on their ENS reverse record, they see exactly the same thing as they always have in the app.

## Security / Supply Chain risk consideration
The `@davatar/react` library uses minimal dependencies (just the `color` package and the `merssene-twister` package, and `ethers-provider`).

## List of features added/changed

- Add `@davatar/react` dependency (small, 7kb)
- Wrap the sushi chef image in the `<Davatar />` component for ENS avatar support

## How Has This Been Tested?

Connected my wallet in the local dev environment and checked that it rendered my avatar correctly.

## Screenshots (if appropriate):
Screen Shot 2021-09-29 at 12 28 52 PM

### CODE REVIEW

**Comment by bigint** [comment]
@LufyCZ @matthewlilley any ideas why its not available in prod?

**Comment by LufyCZ** [comment]
> @LufyCZ @matthewlilley any ideas why its not available in prod?

Available on canary.sushi.com

**Comment by bigint** [comment]
Screenshot 2022-01-15 at 6 30 36 PM

In uniswap

Screenshot 2022-01-15 at 6 31 05 PM

@LufyCZ interesting not working for me 🤔

**Comment by carlosdp** [comment]
They replaced the implementation of ENS avatars away from using this library a few months ago. The code from this PR are no longer in the codebase.

**Comment by LufyCZ** [comment]
Might've been overwritten by a recent merge, will have a look and see what's up

**Comment by bigint** [comment]
@LufyCZ I can create a PR for that 🤗

**Comment by LufyCZ** [comment]
> @LufyCZ I can create a PR for that 🤗 

That'd be great, thanks

**Pull request merged**
