### PR TITLE
Restyle xsushi

### LINKED ISSUE #59: Restyle: xSUSHI Staking
**Operational Preface:**

Open a new branch when ready for review open a PR against **Canary**. Branch should be titled restyle_xsushi and mention this issue
The current implementation can be found at: https://app.sushi.com/staking 
The current page directory can be found at: https://github.com/sushiswap/sushiswap-interface/tree/master/src/pages/SushiBar 

_When submitting the PR please open a new folder under src/pages titled XSushi and co-locate any relevant components within this folder as well._ 

----------------------------------------

**Sample Design Screen:**

xsushi

More design details and assets can be found on Figma Dashboard: https://www.figma.com/file/zibFzATC7X8UEdkGMRPllo/Staking?node-id=51%3A86. If you are unable to access please reply in issue with a email address, additionally the public prototype can also be viewed here: https://www.figma.com/proto/zibFzATC7X8UEdkGMRPllo/Staking?scaling=min-zoom&page-id=51%3A86&node-id=51%3A87

Implement the following pages based on the design above. This issue is for delivering a responsive mockup and you are not expected to integrate with any existing web3 hooks. Existing hooks however, if you choose to wire up this mockup can be found here: https://github.com/sushiswap/sushiswap-interface/blob/master/src/hooks/useSushiBar.ts 

Additionally you will need to update routing to reflect localhost:3000/staking and localhost:3000/unstaking for the relevant screens found in the figma above. You do not need to implement the header as this exists currently on the master branch

Should you need access to new colors in the Figma prototype you can add those colors to the tailwinds configuration file here: https://github.com/sushiswap/sushiswap-interface/blob/master/tailwind.config.js#L23

With regards to gradient buttons you can read the tailwind documentation for the appropriate class notation here: https://tailwindcss.com/docs/gradient-color-stops

### PR DESCRIPTION
**Pull request by JonahGroendal**
Closes #59 

I chose not to wire it up because I wanted to get this PR in before Monday. 

see it at https://sushiswap-interface-git-restylexsushi-teamsushi.vercel.app/staking

Clicking on "stake" in the header/nav menu will bring you to the old page (localhost:3000/stake). I did it this way because the page isn't wired up yet.

### CODE REVIEW

**Comment by omakasebar** [comment]
Hey @JonahGroendal I'm going to go ahead and merge this into canary and wire it up later today. Definitely, no rush for you. Would love for this to be included in our upcoming release

**Comment by JonahGroendal** [comment]
@omakasebar hey sorry it's taking so long. I did wire it up most of the way and added in that Transaction Rejected modal as well. I'll push my commits right now, but it's not quite ready for release. The earnings, APR, and weighted APR still need to be wired up. The `approve` function also needs to be wired up.

**Comment by omakasebar** [comment]
Hey @JonahGroendal no worries - feel free to push what you have and we can work on this on canary branch, let me know when you're ready. Adding the Approve shouldn't take too long for me and the earnings we can fall back to SUSHI balance (since earnings is a little bit more involved - will probably be opened as a new issue). APR I'll pull from the subgraph (won't be weighted APR but average)

**Comment by JonahGroendal** [comment]
@omakasebar Yeah I was going to ask you about those as they weren't in the useSushibar hook, figured it would be a bit more involved. 

As for the approve function, I think the "confirm staking"  button needs to turn into an "approve" button similar to how tho old page works. I tried just sending the approve transaction and the enter (i.e. stake) transaction at the same time but Metamask rejected the second (enter) transaction (even though it would go through if Metamask would just send it).

**Comment by omakasebar** [comment]
@JonahGroendal Yeah makes sense to turn the confirm staking into an approve button. Here's an example of how this pattern is implemented in other pages: https://github.com/sushiswap/sushiswap-interface/blob/master/src/pages/Yield/InputGroup.tsx#L56

**Comment by JonahGroendal** [comment]
@omakasebar I'd like to wire up that `approve` function to make page is usable. Should I keep committing to this branch even though it's merged?

**Comment by omakasebar** [comment]
Hey @JonahGroendal, I actually wired up approve in this commit: https://github.com/sushiswap/sushiswap-interface/commit/2d4607efc3eae46b5f3d1ff0e242cac69149de87, you can see the implementation here: https://github.com/sushiswap/sushiswap-interface/blob/master/src/pages/SushiBar/StakeCard.tsx#L138

Your work is live at https://app.sushi.com/sushibar (!)

**Comment by JonahGroendal** [comment]
Ok great!

**Pull request merged**
