### PR TITLE
[WIP] Implement Faucet Interface

### PR DESCRIPTION
**Pull request by TopETH**
This PR is related with issue #101 

You can see 'claim test tokens' button on AppBar only when you are connected test networks (Goerli, Rinkeby, Ropsten, Kovan)

### CODE REVIEW

**Comment by matthewlilley** [comment]
Thank you for the work on this @TopETH.

It would be great to add some kind of feedback once someone has clicked claim, maybe a link to the pending tx below the button or something. What do you think?

**Comment by omakasebar** [comment]
@TopETH could you rebase this off the latest canary branch? Then we'll merge into there - thanks!

**Comment by TopETH** [comment]
This PR is updated with latest canary branch rebase.

**Comment by omakasebar** [comment]
Thank you!

**Pull request merged**
