### PR TITLE
Bugfix/titles meta desc

### PR DESCRIPTION
**Pull request by chxash**
About https://github.com/sushiswap/sushiswap-interface/issues/295
Minimal change, does not solve the whole problem, but at least twitter cards are showing (https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards)
More work needed in order to update twitter card content.

### CODE REVIEW

**Comment by chillichelli** [comment]
Hi, thank you for your contribution! I looked up key twitter:text:title but can't find any docs on this. Can you link me the docs where you found this twitter:text:title or share some screenshots of the card with before and after? I want to make sure it works

**Comment by matthewlilley** [comment]
Ah yes, @chxash @chillichelli, it looks like that might be an old identifier. I found some references on Google but official docs don't mention it.

https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary

I assume it was replaced with twitter:title?

**Comment by matthewlilley** [comment]
Also @chxash it would be awesome if you could port the changes made in your previous PR which were merged into master, to the canary branch.

**Comment by chxash** [comment]
> Hi, thank you for your contribution! I looked up key twitter:text:title but can't find any docs on this. Can you link me the docs where you found this twitter:text:title or share some screenshots of the card with before and after? I want to make sure it works

Hi @chillichelli , I used https://cards-dev.twitter.com/validator and this is the error we are getting from current master 
card_validator

@matthewlilley I could port the code to canary, twitter cards are showing up with this code but it's not very satisfactory since the texts, images and urls are still not updated on different pages :(

I am investigating how we can fix this, one way that is working for me is to pass meta information through "getStaticProps" method in related components.
I will submit code for this when I have time and maybe it will spark discussion.

**Comment by chxash** [comment]
Changed twitter card from "app" to "summary", seems more appropriate given twitter cards description, also fix images not showing up in last screen

card_validator_fixed2

**Review by chillichelli — APPROVED** [review]

**Comment by matthewlilley** [comment]
Thanks @chxash, this is great. 

One of the main problems is page specific descriptions, images, titles, etc... are not showing in the previews which they should.

**Pull request closed without merging**
