### PR TITLE
Language switch

### PR DESCRIPTION
**Pull request by chillichelli**
Add a language switch with the following languages:
- German
- English
- Spanish (Argentina)
- Spanish (US)
- Italian
- Hebrew
- Romanian
- Russian
- Vietnamese
- Chinese (Traditional)
- Chinse (Simplified)

### CODE REVIEW

**Comment by matthewlilley** [comment]
Hey @chillichelli,

Just pulled this in locally and it works great! The only nit-picky thing I noticed was that the flag text isn't aligned with the rest of the menu items.

Screenshot_740

**Comment by matthewlilley** [comment]
You'll probably want to use Unicode for the flags so they render on every platform.

https://unicode.org/emoji/charts/full-emoji-list.html

**Comment by chillichelli** [comment]
Thanks! I did use the unicode flags but apparently the Segoe UI font on Windows doesn't have the flags included so I converted them to PNGs instead. I added a comment where I converted the flags and with what settings if we ever want to add more languages.

**Comment by matthewlilley** [comment]
> Thanks! I did use the unicode flags but apparently the Segoe UI font on Windows doesn't have the flags included so I converted them to PNGs instead. I added a comment where I converted the flags and with what settings if we ever want to add more languages.

Yeah, I've come across this before actually. That sounds good to me!

**Comment by omakasebar** [comment]
Screen Shot 2021-03-20 at 9 47 01 PM
The image resolution seems a bit poor

**Comment by chillichelli** [comment]
Looks a lot worse on your machine it seems. Deliberately kept the image resolution on the low side so the feature wouldnt add 80kB to the bundle. I'll up the res anyway

**Comment by chillichelli** [comment]
Images now add up to 25kb instead of 8kb

**Comment by omakasebar** [comment]
Looks good!

**Pull request merged**
