### PR TITLE
Restyle PoolFinder

### PR DESCRIPTION
**Pull request by TopETH**
This PR is related with issue #90.

### CODE REVIEW

**Comment by omakasebar** [comment]
Looking good. One small style issue:
style_issue

**Comment by TopETH** [comment]
Style issue is resolved. Please check this PR.

**Comment by matthewlilley** [comment]
Thanks again for the work on this @TopETH

One small thing which would be great to resolve is replacing the tip alert with the new one used on other pages.

**Comment by TopETH** [comment]
This PR is rebased with latest canary again.

**Comment by omakasebar** [comment]
@TopETH will reopen new branch for PR rebased against latest canary to reduce number of commits

**Pull request closed without merging**
