### PR TITLE
Improving UI renders on swap page

### PR DESCRIPTION
**Pull request by grod220**
Video walkthrough: https://www.youtube.com/watch?v=n1qhN486rvA

Problem: swap page modal feels delayed as it pops up and typing

Solution: a pesky JSON.stringify slowing the world down

### CODE REVIEW

**Comment by matthewlilley** [comment]
Awesome @grod220! LGTM

**Comment by chillichelli** [comment]
Ahh yea, that's my doing. I added this as a temporary solution for inari but never got the chance to make for a clean solution. If you got to https://sushiswap-interface-79f2jd9sk-teamsushi.vercel.app/inari there is an infinite loop now. This has something to do with balance being a dep of the useEffect here I think https://github.com/sushiswap/sushiswap-interface/blob/canary/src/state/inari/strategies/useStakeSushiToAaveStrategy.ts#L58

**Comment by grod220** [comment]
@chillichelli ah! Needs more investigation then. Let's revert and I'll keep poking around: https://github.com/sushiswap/sushiswap-interface/pull/341

**Comment by grod220** [comment]
@chillichelli I was definitely mistaken! Those other dependency arrays are looking for new object references. So the memoization indeed returns the same object if the `JSON.stringify(balances)` serializes the same. However, could we do something like`Object.keys(balances).join()`? This way the key would only change if new tokens keys are returned (assuming the content of those objects do not change). Does this make sense to do?

**Comment by chillichelli** [comment]
Hmm better to join values I think or else updated balances won't be reflected. Still feels like a hack tho. Which other dependency arrays are looking for new object references?

**Comment by grod220** [comment]
`useStakeSushiToAaveStrategy`
`useStakeSushiToBentoStrategy`
`useStakeSushiToCreamStrategy`
`useStakeSushiToCreamToBentoStrategy`

It looks like we need to write our own serialization method. Something like this perhaps?

```
const serializeBalances = (balances: { [tokenAddress: string]: CurrencyAmount<Token> | undefined }): string => {
  return Object.entries(balances)
    .map(([address, currencyAmount]) => address + currencyAmount.toExact())
    .join()
}
```

**Comment by grod220** [comment]
(Chatted on discord) -- Will pursue adding the serialization method to the SDK. That way all consumers of CurrencyAmount can make use of it.

**Pull request merged**
